### PR TITLE
fix: title and desc allow multiple edits

### PR DESCRIPTION
**Pull request by saisilinus**
This fix prevents the `Edit title and description` button from disappearing after a single edit

Closes ASKnetCommunity/Training#113

### CODE REVIEW

**Comment by saisilinus** [comment]
I am not sure if this is an issue but when I modified the `style.sass` file, it updated a lot of the CSS files; I only expected it to modify the `style.css`, `style.css.map`, `style.min.css`, and `style.min.css.map` files. Is this how it's supposed to work @bmen?

**Comment by bmen** [comment]
> I am not sure if this is an issue but when I modified the `style.sass` file, it updated a lot of the CSS files; I only expected it to modify the `style.css`, `style.css.map`, `style.min.css`, and `style.min.css.map` files. Is this how it's supposed to work @bmen?

Can you continue working on the basis of my last clean-up? https://github.com/ASKnetCommunity/Training/tree/112-implementing-a-css-library-and-summarize-all-distributed-css-snippets

You will see that I have outsourced the training configurator to a separate SASS file: trainingsplan.sass If you edit this, your Sass converter should generate a min.css and min.css.map to the assets/css folder.

I had written a small readme for this: https://github.com/ASKnetCommunity/Training/tree/112-implementing-a-css-library-and-summarize-all-distributed-css-snippets#styling-css-sass-etc

**Comment by bmen** [comment]
It is better to add the 112-implementing-a-css-library-and-summarise-all-distributed-css-snippets branch locally first:

112-implementing-a-css-library-and-summarise-all-distributed-css-snippets -> 
saisilinus:training-title-description-multiple-edits

and then a new pull request:

saisilinus:training-title-description-multiple-edits -> ASKnetCommunity:development

**Comment by saisilinus** [comment]
> It is better to merge the 112-implementing-a-css-library-and-summarise-all-distributed-css-snippets branch locally first:
> 
> 112-implementing-a-css-library-and-summarise-all-distributed-css-snippets -> saisilinus:training-title-description-multiple-edits
> 
> and then a new pull request:
> 
> saisilinus:training-title-description-multiple-edits -> ASKnetCommunity:development

This will be kinda difficult from my end since I am working on multiple issues each with its separate branch and they all originate from the same starting position which is the latest commit to ASKnetCommunity:development](https://github.com/ASKnetCommunity/Training/tree/development). I am already going to have to deal with merge conflicts as it is so integrating your changes to one of my branches is not really practical.

I think a better solution would be for me to revert the `sass` changes in this commit and just go with inline `CSS` for now since it's just a couple of styles. I can then merge your changes after I've finished with my issues. I won't touch the `sass` files for now.

**Comment by timmwille** [comment]
@saisilinus this now has a merge conflict, sorry. Hope it is easy to fix for you

**Comment by timmwille** [comment]
thx @bmen

**Comment by bmen** [comment]
I have now merged the changes. It is now best to work on all further changes on the basis of development branch. There were a few important changes. One of them is that index.js is now called trainingplan.js.

@saisilinus We can move your CSS code in the HTML to the main.sass later.

**Pull request merged**
