### PR TITLE
Improved Tags generation, Font size, Icons, print view and auto-Daybreak 

### LINKED ISSUE #145: Module Introduction Duration - Correct Abbreviation for Minutes --> min and a space between number and Abbreviation
the correct way would be "**2 min**" instead of "2m", thanks for changing :)
Bildschirmfoto 2023-11-28 um 12 04 21

### PR DESCRIPTION
**Pull request by saisilinus**
Bug fixing and features:
- Update icons
- Cleanup print view
- Improve sidebar
- Fix several bugs
- Add tags autogeneration
- Update font size
- Add insert daybreak after 8 hours

Closes ASKnetCommunity/Training#142, closes ASKnetCommunity/Training#141, closes ASKnetCommunity/Training#96, closes ASKnetCommunity/Training#44, closes #145

### CODE REVIEW

**Comment by saisilinus** [comment]
I've changed the font size to fix #44 but it appears too small on my end. Check and revert @timmwille

**Comment by timmwille** [comment]
Hi @saisilinus sorry it took me so long but I finally managed to check all the changes of this big one.


grafik

So here my findings/requests:

- [ ] Can you start the filter list with a collapsed mode? :star: 
- [ ] The Day Break appears well, but in some cases will be added at the end of a module within a module, though it would make sense then it appears rather always at the end of a module when it is past the last resource? (optional tweak if easy to fix)
- [ ] by that I discovered, when I want to move the Daybreak that was auto-placed, it will generate/copy a new day break instead of moving it! needs a fix
- [ ] the Zoom (out) of the left panel is now really a bit too small on big screens, so maybe reverse it? (I think all other improvements are really nice, especially because now only 3 Lines of the description appear) It will also be addressed by #133

**Comment by saisilinus** [comment]
> Hi @saisilinus sorry it took me so long but I finally managed to check all the changes of this big one.
> 
> grafik
> 
> So here my findings/requests:
> 
> * [ ]  Can you start the filter list with a collapsed mode? ⭐
> * [ ]  The Day Break appears well, but in some cases will be added at the end of a module within a module, though it would make sense then it appears rather always at the end of a module when it is past the last resource? (optional tweak if easy to fix)
> * [ ]  by that I discovered, when I want to move the Daybreak that was auto-placed, it will generate/copy a new day break instead of moving it! needs a fix
> * [ ]  the Zoom (out) of the left panel is now really a bit too small on big screens, so maybe reverse it? (I think all other improvements are really nice, especially because now only 3 Lines of the description appear) It will also be addressed by [New Module Layout on left panel selection #133](https://github.com/ASKnetCommunity/Training/issues/133)
> * [ ]  Can we declare "Day Breaks" without Time? I think if an Introduction is needed, one can simply pull a "Time Slot" in (so it would just have a title edit? is that possible?)
> * [ ]  In the print view the References are no longer displayed with URLs, can you fix that to the way it was before?

Hi @timmwille . I've made some changes.

- [x] Can you start the filter list with a collapsed mode? _This is how it works currently so I am not sure what you want me to change_
- [x]  The Day Break appears well, but in some cases will be added at the end of a module within a module, though it would make sense then it appears rather always at the end of a module when it is past the last resource.
- [x] When I want to move the Daybreak that was auto-placed, it will generate/copy a new day break instead of moving it. _Works well on my end so I am not sure what the problem is._
- [x] The Zoom (out) of the left panel is now really a bit too small on big screens, so maybe reverse it
- [ ] Can we declare "Day Breaks" without Time? I think if an Introduction is needed, one can simply pull a "Time Slot" in (so it would just have a title edit? is that possible?). _This is a new feature request. It would change how daybreaks are used and would lead to a lot of changes. We should save that for a new issue. Also, I think it would be better if you got feedback on this since it would be a **BREAKING** change._
- [x] In the print view the References are no longer displayed with URLs, can you fix that to the way it was before?

**Comment by timmwille** [comment]
@saisilinus I will merge it in now but would be nice to still solve the "Copy-on-Move" Issue when moving a Day Break element from module to in-between modules

**Pull request merged**
