### PR TITLE
if a resource has duration of 0 minutes, don't show minutes at all on the description/right of the resource

### PR DESCRIPTION
**Pull request by saisilinus**
Hides resource duration when the time is 0 minutes

Fixes ASKnetCommunity/Training#8

### CODE REVIEW

**Comment by timmwille** [comment]
Is this PR similar to what is solved via #88 ? and specifically is `res.resource.duration` always a product of the pre-set OR manual time/duration ? (I will also test locally ones I've overlooked the other PRs in detail, but looks good, thank you!)

**Comment by saisilinus** [comment]
> Is this PR similar to what is solved via #88 ? and specifically is `res.resource.duration` always a product of the pre-set OR manual time/duration ? (I will also test locally ones I've overlooked the other PRs in detail, but looks good, thank you!)

Yes, they are similar. #88 builds on this and shows the updated duration too. `res.resource.duration` is always the pre-set duration. The manually changed duration can be displayed though and used in the calculations of the total time.

**Comment by saisilinus** [comment]
> Is this PR similar to what is solved via #88 ? and specifically is `res.resource.duration` always a product of the pre-set OR manual time/duration ? (I will also test locally ones I've overlooked the other PRs in detail, but looks good, thank you!)

You are welcome :grinning:

**Review by timmwille — COMMENTED** [review]
looks clean, I'll check now locally

**Review by timmwille — APPROVED** [review]
ready for development branch

**Comment by timmwille** [comment]
ok looks good. One litte request would be to be discussed: when the module is removed and added again one has no way of resetting to the old time/get a notification of the change?, as it seems the new manual set time is saved

**Comment by saisilinus** [comment]
> ok looks good. One litte request would be to be discussed: when the module is removed and added again one has no way of resetting to the old time/get a notification of the change?, as it seems the new manual set time is saved

I don't fully understand the question. Once you've edited the duration, the new time is only added to the current instance. The actual resource markdown does not change; it still contains the old duration. We could add a button for resetting to the initial time and/or a notification for when the duration changes

**Pull request merged**
